In [18]:
import pandas as pd
import sys
import glob
from pathlib import Path

In [2]:
#path = "../expected_runs/"
#sys.path.append(path)

In [3]:
from expected_runs.generate_gamestate_summary import *

In [35]:
from expected_runs.Helpers import *
from expected_runs.target_and_calculated_pipeline import build_final_dataset
#from generate_gamestate_summary import *
from expected_runs.filter_pitch_type import *
from expected_runs.random_forest_modeling import *

In [5]:
base_path = "../../v3"
years=["2024", "2025"]
out_dir="../results/CSV_files"

In [6]:
pwd

'/home/abhin/projects/01_jack/expected-runs/JupyterNotebook'

In [7]:
summary_df = build_gamestate_summary_all_years(base_path, out_dir)

Processing 2024-02 from local files ...

Processing 2024-03 from local files ...

Processing 2024-04 from local files ...

Processing 2024-05 from local files ...

Processing 2024-06 from local files ...

Processing 2024-07 from local files ...

Processing 2024-08 from local files ...

Processing 2024-09 from local files ...

Processing 2024-10 from local files ...

Processing 2024-11 from local files ...

Processing 2024-12 from local files ...

Processing 2025-01 from local files ...

Processing 2025-02 from local files ...

Processing 2025-03 from local files ...

Processing 2025-04 from local files ...

Processing 2025-05 from local files ...

Processing 2025-06 from local files ...

Processing 2025-07 from local files ...

Processing 2025-08 from local files ...

All-year summary saved: ../results/CSV_files/GameState_Summary_ALL_prob_20260629_1118.csv

In [28]:
summary_path = glob.glob(out_dir + "/GameState_Summary*.csv")
#summary_path="../results/CSV_files/GameState_Summary.csv"
summary_path = summary_path
summary_path

['../results/CSV_files/GameState_Summary_ALL_prob_20260629_1118.csv',
 '../results/CSV_files/GameState_Summary_ALL_prob_20260602_1016.csv',
 '../results/CSV_files/GameState_Summary_ALL_prob_20260601_1605.csv',
 '../results/CSV_files/GameState_Summary_ALL_prob_20260624_1616.csv']

In [11]:
final_df = build_final_dataset(base_path, years, summary_path, out_dir)

Processing year 2024
Processing year 2025
Final dataset saved: ../results/CSV_files/Final_Target_Calc_1201.csv

In [12]:
final_df.head()

,PitchNo,Date,PAofInning,PitchofPA,Pitcher,PitcherId,PitcherThrows,PitcherTeam,Batter,BatterSide,...,Avg_HorzBreak_FastestType,Avg_RelSpeed_FastestType,vertbreakdiff,horzbreakdiff,velocity_differential,VertBreak,PlateLocHeight,PlateLocSide,Level,League
0,1.0,2024-02-09,1.0,1.0,"Avila, Cesar",1.000081e+09,Right,CUM_PAT,"Junker, Noah",Left,...,9.765045,90.629884,0.280553,1.354375,0.221296,-16.16969,0.54762,0.27288,NAIA,NAIA
1,2.0,2024-02-09,1.0,2.0,"Avila, Cesar",1.000081e+09,Right,CUM_PAT,"Junker, Noah",Left,...,9.765045,90.629884,-0.150627,0.555475,0.655266,-15.50910,2.80661,1.36947,NAIA,NAIA
2,3.0,2024-02-09,1.0,3.0,"Avila, Cesar",1.000081e+09,Right,CUM_PAT,"Junker, Noah",Left,...,9.765045,90.629884,-6.131107,3.637005,-10.341544,-31.73368,2.67172,0.58232,NAIA,NAIA
3,4.0,2024-02-09,1.0,4.0,"Avila, Cesar",1.000081e+09,Right,CUM_PAT,"Junker, Noah",Left,...,9.765045,90.629884,0.242723,-0.368265,1.151726,-15.08906,3.05884,0.02117,NAIA,NAIA
4,5.0,2024-02-09,2.0,1.0,"Avila, Cesar",1.000081e+09,Right,CUM_PAT,"Sibert, Gabe",Right,...,9.765045,90.629884,2.507603,-0.442405,1.165276,-13.08162,2.37370,-0.03395,NAIA,NAIA

In [13]:
timestamp = datetime.now().strftime("%Y%m%d_%H%M")

In [20]:
output_dir = Path(out_dir)

In [21]:
ff_output_path = output_dir / f"df_ff_{timestamp}.csv"
ff_output_path

PosixPath('../results/CSV_files/df_ff_20260629_1211.csv')

In [22]:
team_output_path = output_dir / f"df_del_blu_ff_{timestamp}.csv"
team_output_path

PosixPath('../results/CSV_files/df_del_blu_ff_20260629_1211.csv')

In [25]:
ff_output_path, team_output_path = get_timestamped_output_paths(out_dir)

In [32]:
target_paths = glob.glob(out_dir + "/Final_Target_Calc_*.csv")
input_file = target_paths[-1]
input_file

'../results/CSV_files/Final_Target_Calc_1201.csv'

In [31]:
final_df = create_ff_dataset(input_path=input_file, output_path=ff_output_path)

In [33]:
final_df

,PitchNo,Date,PAofInning,PitchofPA,Pitcher,PitcherId,PitcherThrows,PitcherTeam,Batter,BatterSide,...,Avg_RelSpeed_FastestType,vertbreakdiff,horzbreakdiff,velocity_differential,VertBreak,PlateLocHeight,PlateLocSide,Level,League,PitchBucket
0,1.0,2024-02-09,1.0,1.0,"Avila, Cesar",1.000081e+09,Right,CUM_PAT,"Junker, Noah",Left,...,90.629884,0.280553,1.354375,0.221296,-16.16969,0.54762,0.27288,NAIA,NAIA,FourSeamFastball
1,2.0,2024-02-09,1.0,2.0,"Avila, Cesar",1.000081e+09,Right,CUM_PAT,"Junker, Noah",Left,...,90.629884,-0.150627,0.555475,0.655266,-15.50910,2.80661,1.36947,NAIA,NAIA,FourSeamFastball
3,4.0,2024-02-09,1.0,4.0,"Avila, Cesar",1.000081e+09,Right,CUM_PAT,"Junker, Noah",Left,...,90.629884,0.242723,-0.368265,1.151726,-15.08906,3.05884,0.02117,NAIA,NAIA,FourSeamFastball
4,5.0,2024-02-09,2.0,1.0,"Avila, Cesar",1.000081e+09,Right,CUM_PAT,"Sibert, Gabe",Right,...,90.629884,2.507603,-0.442405,1.165276,-13.08162,2.37370,-0.03395,NAIA,NAIA,FourSeamFastball
7,8.0,2024-02-09,2.0,4.0,"Avila, Cesar",1.000081e+09,Right,CUM_PAT,"Sibert, Gabe",Right,...,90.629884,-2.187757,-4.628545,-0.805534,-18.44973,5.11803,0.55275,NAIA,NAIA,FourSeamFastball
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3563840,244.0,2024-05-16,1.0,4.0,"Manning, Grant",1.000128e+09,Right,VIR_TEC,"Whalen, Robert",Right,...,91.231013,-1.026766,0.388798,-0.767473,-19.17214,2.34006,0.03954,D1,ACC,FourSeamFastball
3563841,245.0,2024-05-16,1.0,5.0,"Manning, Grant",1.000128e+09,Right,VIR_TEC,"Whalen, Robert",Right,...,91.231013,-1.135346,0.311238,0.455597,-18.79446,2.48907,-0.07174,D1,ACC,FourSeamFastball
3563847,251.0,2024-05-16,2.0,6.0,"Manning, Grant",1.000128e+09,Right,VIR_TEC,"O'Ferrall, Griff",Right,...,91.231013,0.229774,0.522148,2.227427,-16.06351,3.44298,0.06199,D1,ACC,FourSeamFastball
3563849,253.0,2024-05-16,3.0,1.0,"Manning, Grant",1.000128e+09,Right,VIR_TEC,"Anderson, Ethan",Left,...,91.231013,-0.210036,2.886868,3.132617,-15.94717,2.04500,0.62883,D1,ACC,FourSeamFastball
3563853,257.0,2024-05-16,3.0,5.0,"Manning, Grant",1.000128e+09,Right,VIR_TEC,"Anderson, Ethan",Left,...,91.231013,1.219104,3.824978,3.796327,-13.95670,2.50115,0.01085,D1,ACC,FourSeamFastball

In [42]:
input_paths = glob.glob(out_dir + "/df_ff_*.csv")
input_paths

['../results/CSV_files/df_ff_20260629_1218.csv']

In [ ]:
#model, train_results, test_results = train_random_forest_model(input_path=input_paths[0], model_path=out_dir+f"/model_{timestamp}.csv")

In [45]:
out_dir+f"/model_{timestamp}.csv"

'../results/CSV_files/model_20260629_1211.csv'